Algoritmo "semnome"
// Disciplina   : [Lógica de Programação co JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joao Vitor A. Molinari
// Data atual  : 30/09/2022
Var
  numero,contadora,resultado:inteiro

Inicio
   para contadora de 1 ate 100 passo 1 faca
   resultado<-contadora+contadora
   Escreval("a soma total dos números são:",resultado)
      fimpara
Fimalgoritmo