Algoritmo "semnome"
// Disciplina   : [Lógica de Programação co JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joao Vitor A. MOlinari
// Data atual  : 30/09/2022
Var
  contadora,contadora1:inteiro

Inicio
   para contadora de 59 ate 0 passo -1 faca
      para contadora1 de 59 ate 0 passo -1 faca
         Escreval(contadora," :", contadora1)
      fimpara
   fimpara
Fimalgoritmo