Algoritmo "semnome"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : ler dois valores do teclado e exibir como resposta a divisão dos valores.
// Autor(a)    : Joao Vitor A. Molinari
// Data atual  : 13/09/2022
Var
numero1:real
numero2:real
valor:real


Inicio
escreval("Digite um número:")
leia(numero1)
escreval("Digite outro número:")
leia(numero2)
valor<-numero1/numero2
escreval("O resultado é:",valor)

Fimalgoritmo