Algoritmo "semnome"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : ler as dimensões de um círculo (raio), calcular e escrever a área do círculo.
// Autor(a)    : Joao Vitor A. Molinari
// Data atual  : 13/09/2022
Var
raio:real
valor:real


Inicio
escreval("Digite as dimensões do círculo(raio):")
leia(raio)
valor<-pi*raio^2
escreval("A área do círculo é:",valor,"m")

Fimalgoritmo