Algoritmo "semnome"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : ler as dimensões de um quadrado (lado), calcular e escrever a área do quadrado.
// Autor(a)    : Joao Vitor A. Molinari
// Data atual  : 13/09/2022
Var
numero:real
valor:real


Inicio
escreval("Digite as dimensões do quadrado(lado):")
leia(numero)
valor<-numero^2
escreval("A área do quadrado é:",valor,"m")

Fimalgoritmo