Algoritmo "semnome"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : ler um valor do teclado e exibir como resposta o número sucessor.
// Autor(a)    : Joao Vitor A. Molinari
// Data atual  : 13/09/2022
Var
numero1:inteiro
valor:inteiro


Inicio
escreval("Digite um número:")
leia(numero1)
valor<-numero1+1
escreval("O resultado é:",valor)

Fimalgoritmo